embedly:
  build: ./embedly
  env_file: .env
  user: root
  expose:
    - "7001"
  links:
    - redis
    - statsd
  restart: never 

worker:
  build: ./embedly
  env_file: .env
  links:
    - redis
    - statsd
  command: rq worker -c rq_settings --exception-handler 'rq_exception_handler.ignore_failed_jobs'

nginx:
  build: ./nginx
  links:
    - embedly
  ports:
    - "80:80"
  restart: never 

redis:
  image: redis
  restart: never

statsd:
  build: ./statsd
  tty: true
  expose:
    - "8125"
  ports:
    - "8125:8125"
